// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WasionOne.API.Data;

#nullable disable

namespace WasionOne.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260919184637_RolSuperadmin")]
    partial class RolSuperadmin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WasionOne.API.Models.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Area", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartamentoId = 1,
                            Nombre = "Seguridad Patrimonial"
                        },
                        new
                        {
                            Id = 2,
                            DepartamentoId = 1,
                            Nombre = "EHS"
                        },
                        new
                        {
                            Id = 3,
                            DepartamentoId = 1,
                            Nombre = "IT"
                        },
                        new
                        {
                            Id = 4,
                            DepartamentoId = 2,
                            Nombre = "RH1"
                        },
                        new
                        {
                            Id = 5,
                            DepartamentoId = 2,
                            Nombre = "RH2"
                        });
                });

            modelBuilder.Entity("WasionOne.API.Models.AreaUbicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<int>("UbicacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UbicacionId");

                    b.HasIndex("AreaId", "UbicacionId")
                        .IsUnique();

                    b.ToTable("AreaUbicacion", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AreaId = 3,
                            UbicacionId = 1
                        },
                        new
                        {
                            Id = 2,
                            AreaId = 3,
                            UbicacionId = 2
                        },
                        new
                        {
                            Id = 3,
                            AreaId = 3,
                            UbicacionId = 3
                        },
                        new
                        {
                            Id = 4,
                            AreaId = 3,
                            UbicacionId = 4
                        },
                        new
                        {
                            Id = 5,
                            AreaId = 3,
                            UbicacionId = 5
                        },
                        new
                        {
                            Id = 6,
                            AreaId = 3,
                            UbicacionId = 6
                        },
                        new
                        {
                            Id = 7,
                            AreaId = 3,
                            UbicacionId = 7
                        });
                });

            modelBuilder.Entity("WasionOne.API.Models.AuditoriaEquipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Almacen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Area")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("AreaUbicacionId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoActivo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DescripcionActivo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("FechaImportacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaProgramada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRealizada")
                        .HasColumnType("datetime2");

                    b.Property<string>("Folio")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Responsable")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("Revisados")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AreaUbicacionId");

                    b.HasIndex("Folio")
                        .IsUnique()
                        .HasFilter("[Folio] IS NOT NULL");

                    b.ToTable("AuditoriaEquipo", (string)null);
                });

            modelBuilder.Entity("WasionOne.API.Models.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DireccionId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("DireccionId");

                    b.ToTable("Departamento", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DireccionId = 1,
                            Nombre = "Seguridad"
                        },
                        new
                        {
                            Id = 2,
                            DireccionId = 1,
                            Nombre = "Recursos Humanos"
                        });
                });

            modelBuilder.Entity("WasionOne.API.Models.Direccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Direccion", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Administración Centralizada"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Operaciones"
                        });
                });

            modelBuilder.Entity("WasionOne.API.Models.IncidenteCritico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("AreaUbicacionId")
                        .HasColumnType("int");

                    b.Property<string>("Causa")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Contramedida")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Detalles")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal?>("DuracionHoras")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaImportacion")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<string>("IdFallaOrigen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Linea")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Responsable")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Severidad")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Tipo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AreaUbicacionId");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("IdFallaOrigen")
                        .IsUnique()
                        .HasFilter("[IdFallaOrigen] IS NOT NULL");

                    b.ToTable("IncidenteCritico", (string)null);
                });

            modelBuilder.Entity("WasionOne.API.Models.InventarioEquipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Almacen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Almacenamiento")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("AreaUbicacionId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCompra")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hostname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MacEthernet")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MacWireless")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Procesador")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Ram")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SistemaOperativo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("TerminoGarantia")
                        .HasColumnType("datetime2");

                    b.Property<string>("TipoEquipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UbicacionExacta")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UsuarioAsignado")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("AreaUbicacionId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Serial")
                        .IsUnique();

                    b.ToTable("InventarioEquipo", (string)null);
                });

            modelBuilder.Entity("WasionOne.API.Models.Platica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AreaUbicacionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaImportacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdOrigen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MedioDifusion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ResponsableEnvio")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TemaPolitica")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("AreaUbicacionId");

                    b.HasIndex("IdOrigen")
                        .IsUnique()
                        .HasFilter("[IdOrigen] IS NOT NULL");

                    b.ToTable("Platica", (string)null);
                });

            modelBuilder.Entity("WasionOne.API.Models.Respaldo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaUbicacionId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("FechaImportacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRespaldo")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdOrigen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Responsable")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SistemaAplicacion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SoftwareUtilizado")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TipoRespaldo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AreaUbicacionId");

                    b.HasIndex("IdOrigen")
                        .IsUnique()
                        .HasFilter("[IdOrigen] IS NOT NULL");

                    b.ToTable("Respaldo", (string)null);
                });

            modelBuilder.Entity("WasionOne.API.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Agente")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("AnyDeskEquipo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AreaUbicacionId")
                        .HasColumnType("int");

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Categoria")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CorreoSolicitante")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DepartamentoOrigen")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Elemento")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("EstadoAprobacion")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("EstadoPrimeraRespuesta")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("EstadoResolucion")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Etiquetas")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaImportacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Grupo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("IdTicketOrigen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Impacto")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("InteraccionesAgente")
                        .HasColumnType("int");

                    b.Property<int?>("InteraccionesCliente")
                        .HasColumnType("int");

                    b.Property<string>("NombreSolicitante")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NotaResolucion")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Origen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("RegistroTiempo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ResultadoEncuesta")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("SolicitanteVip")
                        .HasColumnType("bit");

                    b.Property<string>("Subcategoria")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TiempoInicialRespuesta")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("TiempoPrimeraRespuestaHoras")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TiempoResolucionHoras")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipoAsociacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UbicacionSolicitante")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Urgencia")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AreaUbicacionId");

                    b.HasIndex("IdTicketOrigen")
                        .IsUnique()
                        .HasFilter("[IdTicketOrigen] IS NOT NULL");

                    b.ToTable("Ticket", (string)null);
                });

            modelBuilder.Entity("WasionOne.API.Models.Ubicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Ubicacion", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Planta 1"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Planta 2"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Planta 3"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "CDMX"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Acapulco - Soporte Técnico"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Monterrey"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Planta 5"
                        });
                });

            modelBuilder.Entity("WasionOne.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<int?>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<int?>("DireccionId")
                        .HasColumnType("int");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("DireccionId");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            NombreCompleto = "Administrador General",
                            NombreUsuario = "admin",
                            PasswordHash = "100000.eE4Fsv4smUeDOysC5huSKw==.IyukRhjeKxflKPAplF7FfngTa87nIAZrBQTHXpL313w=",
                            Rol = "Superadmin"
                        });
                });

            modelBuilder.Entity("WasionOne.API.Models.UsuarioModulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ModuloClave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "ModuloClave")
                        .IsUnique();

                    b.ToTable("UsuarioModulo", (string)null);
                });

            modelBuilder.Entity("WasionOne.API.Models.Area", b =>
                {
                    b.HasOne("WasionOne.API.Models.Departamento", "Departamento")
                        .WithMany("Areas")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("WasionOne.API.Models.AreaUbicacion", b =>
                {
                    b.HasOne("WasionOne.API.Models.Area", "Area")
                        .WithMany("AreaUbicaciones")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WasionOne.API.Models.Ubicacion", "Ubicacion")
                        .WithMany("AreaUbicaciones")
                        .HasForeignKey("UbicacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("WasionOne.API.Models.AuditoriaEquipo", b =>
                {
                    b.HasOne("WasionOne.API.Models.AreaUbicacion", "AreaUbicacion")
                        .WithMany()
                        .HasForeignKey("AreaUbicacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AreaUbicacion");
                });

            modelBuilder.Entity("WasionOne.API.Models.Departamento", b =>
                {
                    b.HasOne("WasionOne.API.Models.Direccion", "Direccion")
                        .WithMany("Departamentos")
                        .HasForeignKey("DireccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Direccion");
                });

            modelBuilder.Entity("WasionOne.API.Models.IncidenteCritico", b =>
                {
                    b.HasOne("WasionOne.API.Models.AreaUbicacion", "AreaUbicacion")
                        .WithMany()
                        .HasForeignKey("AreaUbicacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WasionOne.API.Models.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AreaUbicacion");

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("WasionOne.API.Models.InventarioEquipo", b =>
                {
                    b.HasOne("WasionOne.API.Models.AreaUbicacion", "AreaUbicacion")
                        .WithMany()
                        .HasForeignKey("AreaUbicacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AreaUbicacion");
                });

            modelBuilder.Entity("WasionOne.API.Models.Platica", b =>
                {
                    b.HasOne("WasionOne.API.Models.AreaUbicacion", "AreaUbicacion")
                        .WithMany()
                        .HasForeignKey("AreaUbicacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AreaUbicacion");
                });

            modelBuilder.Entity("WasionOne.API.Models.Respaldo", b =>
                {
                    b.HasOne("WasionOne.API.Models.AreaUbicacion", "AreaUbicacion")
                        .WithMany()
                        .HasForeignKey("AreaUbicacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AreaUbicacion");
                });

            modelBuilder.Entity("WasionOne.API.Models.Ticket", b =>
                {
                    b.HasOne("WasionOne.API.Models.AreaUbicacion", "AreaUbicacion")
                        .WithMany()
                        .HasForeignKey("AreaUbicacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AreaUbicacion");
                });

            modelBuilder.Entity("WasionOne.API.Models.Usuario", b =>
                {
                    b.HasOne("WasionOne.API.Models.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WasionOne.API.Models.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WasionOne.API.Models.Direccion", "Direccion")
                        .WithMany()
                        .HasForeignKey("DireccionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Area");

                    b.Navigation("Departamento");

                    b.Navigation("Direccion");
                });

            modelBuilder.Entity("WasionOne.API.Models.UsuarioModulo", b =>
                {
                    b.HasOne("WasionOne.API.Models.Usuario", "Usuario")
                        .WithMany("ModulosAsignados")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WasionOne.API.Models.Area", b =>
                {
                    b.Navigation("AreaUbicaciones");
                });

            modelBuilder.Entity("WasionOne.API.Models.Departamento", b =>
                {
                    b.Navigation("Areas");
                });

            modelBuilder.Entity("WasionOne.API.Models.Direccion", b =>
                {
                    b.Navigation("Departamentos");
                });

            modelBuilder.Entity("WasionOne.API.Models.Ubicacion", b =>
                {
                    b.Navigation("AreaUbicaciones");
                });

            modelBuilder.Entity("WasionOne.API.Models.Usuario", b =>
                {
                    b.Navigation("ModulosAsignados");
                });
#pragma warning restore 612, 618
        }
    }
}
