// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WasionOne.API.Data;

#nullable disable

namespace WasionOne.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260913213101_UsuariosYRoles")]
    partial class UsuariosYRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WasionOne.API.Models.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DireccionId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("DireccionId");

                    b.ToTable("Area", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DireccionId = 1,
                            Nombre = "Seguridad"
                        },
                        new
                        {
                            Id = 2,
                            DireccionId = 1,
                            Nombre = "Recursos Humanos"
                        });
                });

            modelBuilder.Entity("WasionOne.API.Models.Direccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Direccion", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Administración Centralizada"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Operaciones"
                        });
                });

            modelBuilder.Entity("WasionOne.API.Models.SubArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("SubArea", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AreaId = 1,
                            Nombre = "Seguridad Patrimonial"
                        },
                        new
                        {
                            Id = 2,
                            AreaId = 1,
                            Nombre = "EHS"
                        },
                        new
                        {
                            Id = 3,
                            AreaId = 1,
                            Nombre = "IT"
                        },
                        new
                        {
                            Id = 4,
                            AreaId = 2,
                            Nombre = "RH1"
                        },
                        new
                        {
                            Id = 5,
                            AreaId = 2,
                            Nombre = "RH2"
                        });
                });

            modelBuilder.Entity("WasionOne.API.Models.SubAreaUbicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SubAreaId")
                        .HasColumnType("int");

                    b.Property<int>("UbicacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UbicacionId");

                    b.HasIndex("SubAreaId", "UbicacionId")
                        .IsUnique();

                    b.ToTable("SubAreaUbicacion", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SubAreaId = 3,
                            UbicacionId = 1
                        },
                        new
                        {
                            Id = 2,
                            SubAreaId = 3,
                            UbicacionId = 2
                        },
                        new
                        {
                            Id = 3,
                            SubAreaId = 3,
                            UbicacionId = 3
                        },
                        new
                        {
                            Id = 4,
                            SubAreaId = 3,
                            UbicacionId = 4
                        },
                        new
                        {
                            Id = 5,
                            SubAreaId = 3,
                            UbicacionId = 5
                        });
                });

            modelBuilder.Entity("WasionOne.API.Models.Ubicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Ubicacion", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Planta 1"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Planta 2"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Planta 3"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "CDMX - Oficina de Ventas"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Acapulco - Soporte Técnico"
                        });
                });

            modelBuilder.Entity("WasionOne.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<int?>("DireccionId")
                        .HasColumnType("int");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SubAreaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("DireccionId");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.HasIndex("SubAreaId");

                    b.ToTable("Usuario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            NombreCompleto = "Administrador General",
                            NombreUsuario = "admin",
                            PasswordHash = "100000.eE4Fsv4smUeDOysC5huSKw==.IyukRhjeKxflKPAplF7FfngTa87nIAZrBQTHXpL313w=",
                            Rol = "CEO"
                        });
                });

            modelBuilder.Entity("WasionOne.API.Models.Area", b =>
                {
                    b.HasOne("WasionOne.API.Models.Direccion", "Direccion")
                        .WithMany("Areas")
                        .HasForeignKey("DireccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Direccion");
                });

            modelBuilder.Entity("WasionOne.API.Models.SubArea", b =>
                {
                    b.HasOne("WasionOne.API.Models.Area", "Area")
                        .WithMany("SubAreas")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("WasionOne.API.Models.SubAreaUbicacion", b =>
                {
                    b.HasOne("WasionOne.API.Models.SubArea", "SubArea")
                        .WithMany("SubAreaUbicaciones")
                        .HasForeignKey("SubAreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WasionOne.API.Models.Ubicacion", "Ubicacion")
                        .WithMany("SubAreaUbicaciones")
                        .HasForeignKey("UbicacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SubArea");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("WasionOne.API.Models.Usuario", b =>
                {
                    b.HasOne("WasionOne.API.Models.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WasionOne.API.Models.Direccion", "Direccion")
                        .WithMany()
                        .HasForeignKey("DireccionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WasionOne.API.Models.SubArea", "SubArea")
                        .WithMany()
                        .HasForeignKey("SubAreaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Area");

                    b.Navigation("Direccion");

                    b.Navigation("SubArea");
                });

            modelBuilder.Entity("WasionOne.API.Models.Area", b =>
                {
                    b.Navigation("SubAreas");
                });

            modelBuilder.Entity("WasionOne.API.Models.Direccion", b =>
                {
                    b.Navigation("Areas");
                });

            modelBuilder.Entity("WasionOne.API.Models.SubArea", b =>
                {
                    b.Navigation("SubAreaUbicaciones");
                });

            modelBuilder.Entity("WasionOne.API.Models.Ubicacion", b =>
                {
                    b.Navigation("SubAreaUbicaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
